import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export async function generateMetadata(): Promise<Metadata> {
  const title = 'New Money - Loan for Business'
  const description = 'Generated by create next app'
  const siteName = ''
  const url = ''
  const logoUrl = ''
  const logoAlt = ''

  return {
    title,
    description,
    keywords: [],
    openGraph: {
      type: 'website',
      title: title,
      description,
      siteName,
      url,
      images: {
        url: logoUrl,
        alt: logoAlt,
      },
    },
    twitter: {
      card: 'summary',
      title,
      description,
      site: siteName,
      images: {
        url: logoUrl,
        alt: logoAlt,
      },
    },
    icons: {
      icon: [
        { type: 'image/x-icon', url: '/favicon.ico' },
        { type: 'image/png', sizes: '16x16', url: '/favicon-16x16.png' },
        { type: 'image/png', sizes: '32x32', url: '/favicon-32x32.png' },
      ],
      apple: [{ sizes: '180x180', url: '/apple-touch-icon.png' }],
    },
    manifest: '/site.webmanifest',
    themeColor: '#ffffff',
  }
}

interface IRootLayoutParams {
  children?: ReactNode
}

const RootLayout = ({ children }: IRootLayoutParams) => {
  return (
    <html lang="th">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

export default RootLayout
